const mongoose = require('mongoose');

const transactionSchema = new mongoose.Schema(
    {
        transactionId: {
            type: String,
            required: true,
            unique: true,
            index: true,
        },

        sender: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Customer',
        },

        receiver: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Customer',
        },

        senderAccount: {
            type: String,
            required: true,
        },

        receiverAccount: {
            type: String,
        },

        // Amount in INR for application display/reporting
        amount: {
            type: Number,
            required: true,
            min: 1
        },

        type: {
            type: String,
            enum: ['Deposit', 'Withdrawal', 'Transfer'],
            required: true,
        },

        description: {
            type: String,
            trim: true,
        },

        status: {
            type: String,
            enum: ['Pending', 'Completed', 'Failed'],
            default: 'Pending',
        },

        // Transaction ID generated by BlockBank smart contract
        blockchainTransactionId: {
            type: Number,
        },

        // Ethereum/Ganache transaction hash
        blockchainHash: {
            type: String,
            trim: true,
        },

        // Ganache block number
        blockNumber: {
            type: Number,
        },

        blockchainNetwork: {
            type: String,
            default: 'Ganache',
        },

        // Cashier who processed deposit/withdrawal
        processedBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Cashier',
        },

        timestamp: {
            type: Date,
            default: Date.now,
        },
    },
    {
        timestamps: true,
    }
);

const Transaction = mongoose.model('Transaction', transactionSchema);

module.exports = Transaction;